# This is a basic workflow to help you get started with Actions

name: arpTemplateDeployment

# Controls when the workflow will run
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  resource_group_name: rg-githubactions
  location: CentralUS
  subscription_id: 09306da1-aefe-4b06-97fd-b410eab9b840
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  armDeployStaging:
    name: Deploy to Staging
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      resource_group_name: rg-staging-githubactions
      location: CentralUS
    environment:
      name: staging

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Login to Azure
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_NPKPROD }}
      
      # Run Azure CLI command to manaully run a deployment
      # - name: Deploy Resource Group ${{ env.resource_group_name }} with AZ CLI
      #   uses: Azure/cli@v1
      #   with: 
      #     inlinescript: |
      #       az deployment sub create --location "CentralUS" --template-file "./arm-templates/resourcegroup.json"

      # Deploy ARM Template
      - name: Deploy Resource Group ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscription_id }} # NPK-NonProd
          region: CentralUS
          template: ./arm-templates/resourcegroup.json
          parameters:
            location=${{ env.location }}
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }} #Does not need to be the RG name

      # Deploy ARM Template for storage account to RG
      - name: Deploy Storage Account to ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscription_id }} # NPK-NonProd
          template: ./arm-templates/storageaccount.json
          parameters: 
            ./arm-templates/storageaccount.parameters.json
            storageAccountName=globostg039
            location=CentralUS
          deploymentName: deploystorageaccount
          deploymentMode: incremental

      - run: echo ${{ steps.storageAccountDeploy.outputs.BlobUri }}

       # Deploy Virtual Machine to RG
      - name: Deploy Virtual Machine
        uses: Azure/arm-deploy@v1
        id: virtualMachineDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscription_id }} # NPK-NonProd
          template: ./arm-templates/virtualmachine.json
          parameters: 
            adminPassword=${{ secrets.UBUNTU_ADMIN_PASSWORD }}
            location=${{ env.location }}
          deploymentName: deployvirtualmachine
          deploymentMode: incremental

#######################################################
###  DEPLOY PRODUCTION
#######################################################

  armDeployProduction:
    name: Deploy to Production
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      resource_group_name: rg-prod-githubactions
      location: CentralUS
    environment:
      name: production

    needs: armDeployStaging

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Login to Azure
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_NPKPROD }}
      
      # Run Azure CLI command to manaully run a deployment
      # - name: Deploy Resource Group ${{ env.resource_group_name }} with AZ CLI
      #   uses: Azure/cli@v1
      #   with: 
      #     inlinescript: |
      #       az deployment sub create --location "CentralUS" --template-file "./arm-templates/resourcegroup.json"

      # Deploy ARM Template
      - name: Deploy Resource Group ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscription_id }} # NPK-NonProd
          region: CentralUS
          template: ./arm-templates/resourcegroup.json
          parameters:
            location=${{ env.location }}
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }} #Does not need to be the RG name

      # Deploy ARM Template for storage account to RG
      - name: Deploy Storage Account to ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscription_id }} # NPK-NonProd
          template: ./arm-templates/storageaccount.json
          parameters: 
            ./arm-templates/storageaccount.parameters.json
            storageAccountName=globostg065
            location=CentralUS
          deploymentName: deploystorageaccount
          deploymentMode: incremental

      - run: echo ${{ steps.storageAccountDeploy.outputs.BlobUri }}

       # Deploy Virtual Machine to RG
      - name: Deploy Virtual Machine
        uses: Azure/arm-deploy@v1
        id: virtualMachineDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscription_id }} # NPK-NonProd
          template: ./arm-templates/virtualmachine.json
          parameters: 
            adminPassword=${{ secrets.UBUNTU_ADMIN_PASSWORD }}
            location=${{ env.location }}
          deploymentName: deployvirtualmachine
          deploymentMode: incremental
